# Generated by Django 2.1.3 on 2018-11-05 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCollectionEvent',
            fields=[
                ('colleventid', models.CharField(db_column='CollEventID', max_length=45, primary_key=True, serialize=False)),
                ('collevent_date', models.DateField(blank=True, db_column='CollEventDate', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_collection_event',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCollector',
            fields=[
                ('collectorid', models.IntegerField(db_column='CollectorID', primary_key=True, serialize=False)),
                ('collectorType', models.DateField(blank=True, db_column='CollectorType', null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_collector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblCruise',
            fields=[
                ('cruiseid', models.CharField(db_column='CruiseID', max_length=45, primary_key=True, serialize=False)),
                ('cruise_start', models.DateField(blank=True, db_column='CruiseStart', null=True)),
                ('cruise_end', models.DateField(blank=True, db_column='CruiseEnd', null=True)),
                ('vessel', models.CharField(blank=True, db_column='Vessel', max_length=45, null=True)),
                ('region', models.CharField(blank=True, db_column='Region', max_length=45, null=True)),
                ('chief_scientist', models.CharField(blank=True, db_column='ChiefScientist', max_length=45, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=100, null=True)),
            ],
            options={
                'db_table': 'tbl_cruise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblEnvironmental',
            fields=[
                ('environmentalid', models.CharField(db_column='EnvironmentalID', max_length=45, primary_key=True, serialize=False)),
                ('environmental_datetime', models.DateTimeField(blank=True, db_column='DateTime24-GMT', null=True)),
                ('sampler', models.CharField(blank=True, db_column='Sampler', max_length=25, null=True)),
                ('depth_discrete', models.IntegerField(blank=True, db_column='DepthDiscrete', null=True)),
                ('depth_min', models.IntegerField(blank=True, db_column='DepthMin', null=True)),
                ('depth_max', models.IntegerField(blank=True, db_column='DepthMax', null=True)),
                ('latitude', models.DecimalField(blank=True, db_column='Latitude', decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, db_column='Longitude', decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('colleventid', models.ForeignKey(db_column='CollEventID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblCollectionEvent')),
            ],
        ),
        migrations.CreateModel(
            name='TblLab',
            fields=[
                ('labid', models.IntegerField(db_column='LabID', primary_key=True, serialize=False)),
                ('labname', models.CharField(db_column='LabName', max_length=30)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('contactname', models.CharField(blank=True, db_column='ContactName', max_length=30, null=True)),
                ('contactemail', models.CharField(blank=True, db_column='ContactEmail', max_length=30, null=True)),
                ('contactphone', models.CharField(blank=True, db_column='ContactPhone', max_length=12, null=True)),
            ],
            options={
                'db_table': 'tbl_lab',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblLocation',
            fields=[
                ('locationid', models.IntegerField(db_column='LocationID', primary_key=True, serialize=False)),
                ('institution', models.CharField(db_column='Institution', max_length=50)),
                ('location', models.CharField(db_column='Location', max_length=50)),
            ],
            options={
                'db_table': 'tbl_location',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblOriginTypes',
            fields=[
                ('origintypeid', models.IntegerField(db_column='OriginID', primary_key=True, serialize=False)),
                ('originname', models.CharField(db_column='SubsampleType', max_length=20)),
            ],
            options={
                'db_table': 'tbl_origin_types',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsBulkStableIsotope',
            fields=[
                ('r6id', models.IntegerField(db_column='R6ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('analyzedby', models.CharField(blank=True, db_column='AnalyzedBy', max_length=30, null=True)),
                ('hedilution', models.CharField(blank=True, db_column='HeDilution', max_length=30, null=True)),
                ('notes', models.TextField(blank=True, db_column='Notes', null=True)),
                ('EA_mass_mg', models.FloatField(blank=True, db_column='EA_mass_mg', null=True)),
                ('n_ug', models.FloatField(blank=True, db_column='N_ug', null=True)),
                ('d15n', models.FloatField(blank=True, db_column='d15N', null=True)),
                ('c_ug', models.FloatField(blank=True, db_column='C_ug', null=True)),
                ('d13c', models.FloatField(blank=True, db_column='d13C', null=True)),
                ('acidified', models.BooleanField(db_column='Acidified', default=False)),
                ('molarcn', models.FloatField(blank=True, db_column='MolarCN', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('replicates', models.BooleanField(db_column='Replicates', default=False)),
            ],
            options={
                'db_table': 'tbl_results_bulk_stable_isotope',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsCompSpecAaIsotope',
            fields=[
                ('r5id', models.IntegerField(db_column='R5ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('runnum', models.CharField(db_column='RunNum', max_length=20)),
                ('aminoacid', models.CharField(blank=True, db_column='AminoAcid', max_length=20, null=True)),
                ('ea_irms', models.FloatField(blank=True, db_column='EA-IRMS', null=True)),
                ('rt', models.FloatField(blank=True, db_column='RT', null=True)),
                ('peak', models.IntegerField(blank=True, db_column='Peak', null=True)),
                ('rt2', models.FloatField(blank=True, db_column='RT2', null=True)),
                ('area', models.FloatField(blank=True, db_column='Area', null=True)),
                ('d15n_un', models.FloatField(blank=True, db_column='d15N_un', null=True)),
                ('d15n_std', models.FloatField(blank=True, db_column='d15N_std', null=True)),
                ('d15n_reg', models.FloatField(blank=True, db_column='d15N_reg', null=True)),
                ('standard', models.CharField(blank=True, db_column='Standard', max_length=30, null=True)),
                ('vialid', models.CharField(blank=True, db_column='VialID', max_length=20, null=True)),
                ('sampleweight', models.FloatField(blank=True, db_column='SampleWeight', null=True)),
                ('ea_ul', models.IntegerField(blank=True, db_column='EA_uL', null=True)),
                ('injectionvolume', models.FloatField(blank=True, db_column='InjectionVolume', null=True)),
            ],
            options={
                'db_table': 'tbl_results_comp_spec_AA_isotope',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsFattyAcid',
            fields=[
                ('r4id', models.IntegerField(db_column='R4ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('csiro_id', models.TextField(db_column='CSIRO_ID')),
                ('noaa_ll_specimenid', models.TextField(db_column='NOAA_LL_SpecimenID')),
                ('tissuetype', models.CharField(blank=True, db_column='TissueType', max_length=20, null=True)),
                ('tissuelocation', models.CharField(blank=True, db_column='TissueLocation', max_length=20, null=True)),
                ('catchdate', models.DateField(blank=True, db_column='CatchDate', null=True)),
                ('forklength_cm', models.FloatField(blank=True, db_column='Forklength_cm', null=True)),
                ('wholemass_g', models.FloatField(blank=True, db_column='WholeMass_g', null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=1, null=True)),
                ('drymass_g', models.FloatField(blank=True, db_column='DryMass_g', null=True)),
                ('caplessvialandlipid_g', models.FloatField(blank=True, db_column='CaplessVialAndLipid_g', null=True)),
                ('caplessvial_g', models.FloatField(blank=True, db_column='CaplessVial_g', null=True)),
                ('lipidmass_g', models.FloatField(blank=True, db_column='LipidMass_g', null=True)),
                ('lipidmass_mg', models.FloatField(blank=True, db_column='LipidMass_mg', null=True)),
                ('c19_internal_standard_added_ul', models.IntegerField(blank=True, db_column='C19_Internal_Standard_Added_ul', null=True)),
                ('percentlipid_drywt', models.FloatField(blank=True, db_column='PercentLipid_drywt', null=True)),
                ('methylation_ul', models.IntegerField(blank=True, db_column='Methylation_ul', null=True)),
                ('tl_volume_ul', models.IntegerField(blank=True, db_column='TL_Volume_ul', null=True)),
                ('percentlipid_drywt_reweigh', models.FloatField(blank=True, db_column='PercentLipid_drywt_reweigh', null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'tbl_results_fattyacid',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsFreezedry',
            fields=[
                ('r3id', models.IntegerField(db_column='R3ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('family', models.TextField(blank=True, db_column='Family', null=True)),
                ('genus', models.TextField(blank=True, db_column='Genus', null=True)),
                ('species', models.TextField(blank=True, db_column='Species', null=True)),
                ('counts', models.IntegerField(blank=True, db_column='Counts', null=True)),
                ('length1_type', models.CharField(blank=True, db_column='Length1_type', max_length=20, null=True)),
                ('length1_mm', models.IntegerField(blank=True, db_column='Length1_mm', null=True)),
                ('length2_type', models.CharField(blank=True, db_column='Length2_type', max_length=20, null=True)),
                ('length2_mm', models.IntegerField(blank=True, db_column='Length2_mm', null=True)),
                ('wholewetmass', models.IntegerField(blank=True, db_column='WholeWetMass', null=True)),
                ('wetremaining', models.TextField(blank=True, db_column='WetRemaining', null=True)),
                ('vessel', models.FloatField(blank=True, db_column='Vessel', null=True)),
                ('vesselandwet', models.FloatField(blank=True, db_column='VesselAndWet', null=True)),
                ('vesselanddry', models.FloatField(blank=True, db_column='VesselAndDry', null=True)),
                ('percentwater', models.FloatField(blank=True, db_column='PercentWater', null=True)),
                ('drytissue', models.FloatField(blank=True, db_column='DryTissue', null=True)),
                ('drytissuetype', models.CharField(blank=True, db_column='DryTissueType', max_length=30, null=True)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'tbl_results_freezedry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsMercury1',
            fields=[
                ('r1id', models.IntegerField(db_column='R1ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('weight', models.FloatField(db_column='Weight')),
                ('height', models.FloatField(db_column='Height')),
                ('hg_ng', models.FloatField(db_column='Hg_ng')),
                ('dryc_ugkg', models.FloatField(db_column='DryC_ugkg')),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
            ],
            options={
                'db_table': 'tbl_results_mercury_1',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblResultsMercury2',
            fields=[
                ('r2id', models.IntegerField(db_column='R2ID', primary_key=True, serialize=False)),
                ('analysisdate', models.DateField(db_column='AnalysisDate')),
                ('drylogid', models.CharField(blank=True, db_column='DryLogID', max_length=15, null=True)),
                ('aliquotmass_g', models.FloatField(blank=True, db_column='AliquotMass_g', null=True)),
                ('hg_ugg_wet', models.FloatField(blank=True, db_column='Hg_ugg_wet', null=True)),
                ('batch', models.CharField(blank=True, db_column='Batch', max_length=10, null=True)),
                ('flag', models.TextField(blank=True, db_column='Flag', null=True)),
            ],
            options={
                'db_table': 'tbl_results_mercury_2',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSample',
            fields=[
                ('sampleid', models.IntegerField(db_column='SampleID', primary_key=True, serialize=False)),
                ('acsampleid', models.CharField(blank=True, db_column='ACSampleID', max_length=45, null=True)),
                ('originid', models.IntegerField(blank=True, db_column='SampleOriginID', default=0, null=True)),
                ('processingid', models.CharField(blank=True, db_column='ProcessingID', max_length=20, null=True)),
                ('length1_mm', models.FloatField(blank=True, db_column='Length1_MM', null=True)),
                ('length1_type', models.CharField(blank=True, db_column='Length1_type', max_length=20, null=True)),
                ('length2_mm', models.FloatField(blank=True, db_column='Length2_MM', null=True)),
                ('length2_type', models.CharField(blank=True, db_column='Length2_type', max_length=20, null=True)),
                ('wet_whole_mass_g', models.FloatField(blank=True, db_column='Wet_Whole_Mass_G', null=True)),
                ('n_individuals', models.IntegerField(db_column='N_Individuals', default=1)),
                ('tissuetype', models.CharField(blank=True, db_column='TissueType', max_length=20, null=True)),
                ('remaining_mass_g', models.FloatField(blank=True, db_column='Remaining_Mass_G', null=True)),
                ('environmentalid', models.ForeignKey(db_column='EnvironmentalID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblEnvironmental')),
                ('origin_type', models.ForeignKey(db_column='OriginID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblOriginTypes')),
            ],
            options={
                'db_table': 'tbl_sample',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblSampleTests',
            fields=[
                ('sampletestid', models.IntegerField(db_column='SampleTestID', primary_key=True, serialize=False)),
                ('resultid', models.IntegerField(blank=True, db_column='ResultID', null=True)),
                ('testsent', models.DateField(blank=True, db_column='TestSent', null=True)),
                ('resultrecd', models.DateField(blank=True, db_column='ResultRecd', null=True)),
                ('qaqc', models.BooleanField(db_column='QAQC', default=False)),
                ('comments', models.TextField(blank=True, db_column='Comments', null=True)),
                ('sampleid', models.ForeignKey(db_column='SampleID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSample')),
            ],
            options={
                'db_table': 'tbl_sample_tests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTaxonomy',
            fields=[
                ('taxonomyid', models.CharField(db_column='TaxonomyID', max_length=45, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, db_column='Category', max_length=20, null=True)),
                ('animal', models.CharField(blank=True, db_column='Animal', max_length=20, null=True)),
                ('phylum', models.CharField(blank=True, db_column='Phylum', max_length=20, null=True)),
                ('subphylum', models.CharField(blank=True, db_column='Subphylum', max_length=20, null=True)),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=20, null=True)),
                ('order_field', models.CharField(blank=True, db_column='Order_', max_length=20, null=True)),
                ('family', models.CharField(blank=True, db_column='Family', max_length=20, null=True)),
                ('genus', models.CharField(blank=True, db_column='Genus', max_length=20, null=True)),
                ('species', models.CharField(blank=True, db_column='Species', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tbl_taxonomy',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblTests',
            fields=[
                ('testid', models.IntegerField(db_column='TestID', primary_key=True, serialize=False)),
                ('testtype', models.CharField(db_column='TestType', max_length=20)),
                ('resulttable', models.CharField(db_column='ResultTable', max_length=20)),
                ('labid', models.ForeignKey(db_column='LabID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblLab')),
            ],
            options={
                'db_table': 'tbl_tests',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='tblsampletests',
            name='testid',
            field=models.ForeignKey(db_column='TestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblTests'),
        ),
        migrations.AddField(
            model_name='tblsample',
            name='taxonomyid',
            field=models.ForeignKey(db_column='TaxonomyID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblTaxonomy'),
        ),
        migrations.AddField(
            model_name='tblresultsmercury2',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tblresultsmercury1',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tblresultsfreezedry',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tblresultsfattyacid',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tblresultscompspecaaisotope',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tblresultsbulkstableisotope',
            name='sampletestid',
            field=models.ForeignKey(db_column='SampleTestID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSampleTests'),
        ),
        migrations.AddField(
            model_name='tbllocation',
            name='sampleid',
            field=models.ForeignKey(db_column='SampleID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblSample'),
        ),
        migrations.AddField(
            model_name='tblcollector',
            name='cruiseid',
            field=models.ForeignKey(db_column='CruiseID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblCruise'),
        ),
        migrations.AddField(
            model_name='tblcollectionevent',
            name='collectorid',
            field=models.ForeignKey(db_column='CollectorID', on_delete=django.db.models.deletion.DO_NOTHING, to='deepseaweb.TblCollector'),
        ),
    ]
