# Generated by Django 2.0.5 on 2018-08-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseaweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbltaxonomicid',
            name='extra',
            field=models.CharField(blank=True, db_column='Extra', max_length=20, null=True),
        ),
    ]
