# Generated by Django 2.0.5 on 2018-11-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseaweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltaxonomy',
            name='family',
            field=models.CharField(blank=True, db_column='Family', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbltaxonomy',
            name='genus',
            field=models.CharField(blank=True, db_column='Genus', max_length=50, null=True),
        ),
    ]
