# Generated by Django 2.0.5 on 2018-11-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deepseaweb', '0002_auto_20181107_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbltaxonomy',
            name='suborder',
            field=models.CharField(blank=True, db_column='SubOrder', max_length=40, null=True),
        ),
    ]
